### ISSUE TITLE
Upgrade Data Download Link from HTTP to HTTPS

### ISSUE THREAD

**Issue by saglamutku** [NXP/eiq-model-zoo#1]
Hello,

I noticed that in the repository, the data download link for the mini-speech commands dataset is currently using HTTP https://github.com/NXP/eiq-model-zoo/blob/e2152edd3f729b4772a8328f5745978f51b2b707/tasks/audio/command-recognition/micro-speech-LSTM/scripts/dataset.py#L22-L28, which poses a security risk. Since our server, like many others, strictly connects via HTTPS, it's unable to access the data due to this non-secure connection. To address this issue and ensure secure data transfer, I suggest updating the download link to HTTPS.

Fix:
To resolve this issue, simply update the data download link from:
`http://storage.googleapis.com/download.tensorflow.org/data/mini_speech_commands.zip`
to:
`https://storage.googleapis.com/download.tensorflow.org/data/mini_speech_commands.zip`

With this adjustment, I was able to successfully download the data and run the code. Additionally, this minor adjustment ensures that the data is downloaded securely via HTTPS, eliminating any potential security concerns.

Best regards

**Comment by saglamutku** [comment]
Could you also revise all the other datasets? Some of them also have http links.

**Comment by gaetanbahl** [comment]
Hi @utkusaglm, thank you for pointing this out! 

I fixed all links in the "fix_https" branch so you can use it right away. It will be fixed in the main branch in the next release (next month).

**Comment by saglamutku** [comment]
Hi @gaetanbahl, thanks a lot!
